<?php

namespace App\Service;

class GemDatabase
{
    /**
     * Maps Gem Enchantment ID => [item_id, name, icon, quality]
     */
    public const GEMS = [
        2787 => ['item_id' => 41386, 'name' => 'Spiked Titansteel Helm', 'icon' => 'inv_helmet_134', 'quality' => 4],
        2843 => ['item_id' => 41388, 'name' => 'Brilliant Titansteel Helm', 'icon' => 'inv_helmet_134', 'quality' => 4],
        3302 => ['item_id' => 41387, 'name' => 'Tempered Titansteel Helm', 'icon' => 'inv_helmet_134', 'quality' => 4],
        3371 => ['item_id' => 39900, 'name' => 'Bold Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3374 => ['item_id' => 39905, 'name' => 'Delicate Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3375 => ['item_id' => 39906, 'name' => 'Bright Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3376 => ['item_id' => 39907, 'name' => 'Subtle Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3377 => ['item_id' => 39908, 'name' => 'Flashing Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3378 => ['item_id' => 39909, 'name' => 'Fractured Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3379 => ['item_id' => 39910, 'name' => 'Precise Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3380 => ['item_id' => 39911, 'name' => 'Runed Bloodstone', 'icon' => 'inv_jewelcrafting_gem_22', 'quality' => 2],
        3446 => ['item_id' => 39996, 'name' => 'Bold Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3447 => ['item_id' => 39997, 'name' => 'Delicate Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3448 => ['item_id' => 39998, 'name' => 'Runed Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3449 => ['item_id' => 39999, 'name' => 'Bright Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3450 => ['item_id' => 40000, 'name' => 'Subtle Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3451 => ['item_id' => 40001, 'name' => 'Flashing Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3452 => ['item_id' => 40002, 'name' => 'Fractured Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3453 => ['item_id' => 40003, 'name' => 'Precise Scarlet Ruby', 'icon' => 'inv_jewelcrafting_gem_28', 'quality' => 3],
        3454 => ['item_id' => 40008, 'name' => 'Solid Sky Sapphire', 'icon' => 'inv_jewelcrafting_gem_27', 'quality' => 3],
        3455 => ['item_id' => 40009, 'name' => 'Sparkling Sky Sapphire', 'icon' => 'inv_jewelcrafting_gem_27', 'quality' => 3],
        3456 => ['item_id' => 40010, 'name' => 'Lustrous Sky Sapphire', 'icon' => 'inv_jewelcrafting_gem_27', 'quality' => 3],
        3457 => ['item_id' => 40011, 'name' => 'Stormy Sky Sapphire', 'icon' => 'inv_jewelcrafting_gem_27', 'quality' => 3],
        3458 => ['item_id' => 40012, 'name' => 'Brilliant Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3459 => ['item_id' => 40013, 'name' => 'Smooth Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3460 => ['item_id' => 40014, 'name' => 'Rigid Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3461 => ['item_id' => 40015, 'name' => 'Thick Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3462 => ['item_id' => 40016, 'name' => 'Mystic Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3463 => ['item_id' => 40017, 'name' => 'Quick Autumn\'s Glow', 'icon' => 'inv_jewelcrafting_gem_26', 'quality' => 3],
        3464 => ['item_id' => 40022, 'name' => 'Sovereign Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3465 => ['item_id' => 40023, 'name' => 'Shifting Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3466 => ['item_id' => 40025, 'name' => 'Glowing Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3467 => ['item_id' => 40029, 'name' => 'Balanced Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3468 => ['item_id' => 40031, 'name' => 'Regal Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3469 => ['item_id' => 40032, 'name' => 'Defender\'s Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3470 => ['item_id' => 40033, 'name' => 'Puissant Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3471 => ['item_id' => 40034, 'name' => 'Guardian\'s Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3472 => ['item_id' => 40026, 'name' => 'Purified Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3473 => ['item_id' => 40027, 'name' => 'Royal Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3474 => ['item_id' => 40024, 'name' => 'Tenuous Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3475 => ['item_id' => 40030, 'name' => 'Infused Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3476 => ['item_id' => 40028, 'name' => 'Mysterious Twilight Opal', 'icon' => 'inv_jewelcrafting_gem_29', 'quality' => 3],
        3477 => ['item_id' => 40037, 'name' => 'Inscribed Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3478 => ['item_id' => 40038, 'name' => 'Etched Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3479 => ['item_id' => 40039, 'name' => 'Champion\'s Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3480 => ['item_id' => 40040, 'name' => 'Resplendent Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3481 => ['item_id' => 40041, 'name' => 'Fierce Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3482 => ['item_id' => 40043, 'name' => 'Deadly Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3483 => ['item_id' => 40044, 'name' => 'Glinting Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3484 => ['item_id' => 40045, 'name' => 'Lucent Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3485 => ['item_id' => 40046, 'name' => 'Deft Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3486 => ['item_id' => 40047, 'name' => 'Luminous Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3487 => ['item_id' => 40048, 'name' => 'Potent Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3488 => ['item_id' => 40049, 'name' => 'Veiled Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3489 => ['item_id' => 40050, 'name' => 'Durable Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3490 => ['item_id' => 40051, 'name' => 'Reckless Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3491 => ['item_id' => 40052, 'name' => 'Wicked Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3492 => ['item_id' => 40053, 'name' => 'Pristine Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3493 => ['item_id' => 40054, 'name' => 'Empowered Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3494 => ['item_id' => 40055, 'name' => 'Stark Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3495 => ['item_id' => 40056, 'name' => 'Stalwart Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3496 => ['item_id' => 40057, 'name' => 'Glimmering Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3497 => ['item_id' => 40058, 'name' => 'Accurate Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3498 => ['item_id' => 40059, 'name' => 'Resolute Monarch Topaz', 'icon' => 'inv_jewelcrafting_gem_30', 'quality' => 3],
        3518 => ['item_id' => 40111, 'name' => 'Bold Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3519 => ['item_id' => 40112, 'name' => 'Delicate Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3520 => ['item_id' => 40113, 'name' => 'Runed Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3521 => ['item_id' => 40114, 'name' => 'Bright Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3522 => ['item_id' => 40115, 'name' => 'Subtle Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3523 => ['item_id' => 40116, 'name' => 'Flashing Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3524 => ['item_id' => 40118, 'name' => 'Precise Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3525 => ['item_id' => 40117, 'name' => 'Fractured Cardinal Ruby', 'icon' => 'inv_jewelcrafting_gem_37', 'quality' => 4],
        3526 => ['item_id' => 40123, 'name' => 'Brilliant King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3527 => ['item_id' => 40124, 'name' => 'Smooth King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3528 => ['item_id' => 40125, 'name' => 'Rigid King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3529 => ['item_id' => 40126, 'name' => 'Thick King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3530 => ['item_id' => 40127, 'name' => 'Mystic King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3531 => ['item_id' => 40128, 'name' => 'Quick King\'s Amber', 'icon' => 'inv_jewelcrafting_gem_38', 'quality' => 4],
        3532 => ['item_id' => 40119, 'name' => 'Solid Majestic Zircon', 'icon' => 'inv_jewelcrafting_gem_42', 'quality' => 4],
        3533 => ['item_id' => 40120, 'name' => 'Sparkling Majestic Zircon', 'icon' => 'inv_jewelcrafting_gem_42', 'quality' => 4],
        3534 => ['item_id' => 40121, 'name' => 'Lustrous Majestic Zircon', 'icon' => 'inv_jewelcrafting_gem_42', 'quality' => 4],
        3535 => ['item_id' => 40122, 'name' => 'Stormy Majestic Zircon', 'icon' => 'inv_jewelcrafting_gem_42', 'quality' => 4],
        3536 => ['item_id' => 40129, 'name' => 'Sovereign Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3537 => ['item_id' => 40130, 'name' => 'Shifting Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3538 => ['item_id' => 40132, 'name' => 'Glowing Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3539 => ['item_id' => 40136, 'name' => 'Balanced Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3540 => ['item_id' => 40138, 'name' => 'Regal Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3541 => ['item_id' => 40139, 'name' => 'Defender\'s Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3542 => ['item_id' => 40141, 'name' => 'Guardian\'s Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3543 => ['item_id' => 40140, 'name' => 'Puissant Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3544 => ['item_id' => 40131, 'name' => 'Tenuous Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3545 => ['item_id' => 40133, 'name' => 'Purified Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3546 => ['item_id' => 40134, 'name' => 'Royal Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3547 => ['item_id' => 40137, 'name' => 'Infused Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3548 => ['item_id' => 40135, 'name' => 'Mysterious Dreadstone', 'icon' => 'inv_jewelcrafting_gem_40', 'quality' => 4],
        3549 => ['item_id' => 40142, 'name' => 'Inscribed Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3550 => ['item_id' => 40143, 'name' => 'Etched Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3551 => ['item_id' => 40144, 'name' => 'Champion\'s Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3552 => ['item_id' => 40145, 'name' => 'Resplendent Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3553 => ['item_id' => 40146, 'name' => 'Fierce Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3554 => ['item_id' => 40147, 'name' => 'Deadly Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3555 => ['item_id' => 40148, 'name' => 'Glinting Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3556 => ['item_id' => 40149, 'name' => 'Lucent Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3557 => ['item_id' => 40150, 'name' => 'Deft Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3558 => ['item_id' => 40151, 'name' => 'Luminous Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3559 => ['item_id' => 40152, 'name' => 'Potent Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3560 => ['item_id' => 40153, 'name' => 'Veiled Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3561 => ['item_id' => 40154, 'name' => 'Durable Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3563 => ['item_id' => 40155, 'name' => 'Reckless Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3564 => ['item_id' => 40156, 'name' => 'Wicked Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3565 => ['item_id' => 40157, 'name' => 'Pristine Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3566 => ['item_id' => 40158, 'name' => 'Empowered Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3567 => ['item_id' => 40159, 'name' => 'Stark Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3568 => ['item_id' => 40160, 'name' => 'Stalwart Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3569 => ['item_id' => 40161, 'name' => 'Glimmering Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3570 => ['item_id' => 40162, 'name' => 'Accurate Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3571 => ['item_id' => 40163, 'name' => 'Resolute Ametrine', 'icon' => 'inv_jewelcrafting_gem_39', 'quality' => 4],
        3572 => ['item_id' => 40164, 'name' => 'Timeless Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3573 => ['item_id' => 40165, 'name' => 'Jagged Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3574 => ['item_id' => 40166, 'name' => 'Vivid Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3575 => ['item_id' => 40167, 'name' => 'Enduring Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3576 => ['item_id' => 40168, 'name' => 'Steady Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3577 => ['item_id' => 40169, 'name' => 'Forceful Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3578 => ['item_id' => 40170, 'name' => 'Seer\'s Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3579 => ['item_id' => 40171, 'name' => 'Misty Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3580 => ['item_id' => 40172, 'name' => 'Shining Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3581 => ['item_id' => 40173, 'name' => 'Turbid Eye of Zul', 'icon' => 'inv_jewelcrafting_gem_41', 'quality' => 4],
        3621 => ['item_id' => 41285, 'name' => 'Chaotic Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3622 => ['item_id' => 41375, 'name' => 'Destructive Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3623 => ['item_id' => 41334, 'name' => 'Ember Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3624 => ['item_id' => 41374, 'name' => 'Tireless Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3625 => ['item_id' => 41335, 'name' => 'Swift Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3626 => ['item_id' => 41395, 'name' => 'Bracing Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3627 => ['item_id' => 41401, 'name' => 'Insightful Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3628 => ['item_id' => 41398, 'name' => 'Relentless Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3629 => ['item_id' => 41339, 'name' => 'Enigmatic Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3631 => ['item_id' => 41396, 'name' => 'Eternal Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3633 => ['item_id' => 41376, 'name' => 'Revitalizing Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3634 => ['item_id' => 41377, 'name' => 'Effulgent Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3635 => ['item_id' => 41378, 'name' => 'Forlorn Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3636 => ['item_id' => 41379, 'name' => 'Impassive Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3637 => ['item_id' => 41380, 'name' => 'Austere Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3638 => ['item_id' => 41381, 'name' => 'Persistent Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3639 => ['item_id' => 41382, 'name' => 'Trenchant Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3640 => ['item_id' => 41385, 'name' => 'Invigorating Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3641 => ['item_id' => 41389, 'name' => 'Beaming Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3642 => ['item_id' => 41397, 'name' => 'Powerful Earthsiege Diamond', 'icon' => 'inv_jewelcrafting_shadowspirit_02', 'quality' => 3],
        3643 => ['item_id' => 41400, 'name' => 'Thundering Skyflare Diamond', 'icon' => 'inv_jewelcrafting_icediamond_02', 'quality' => 3],
        3732 => ['item_id' => 42142, 'name' => 'Bold Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3733 => ['item_id' => 42143, 'name' => 'Delicate Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3734 => ['item_id' => 42144, 'name' => 'Runed Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3735 => ['item_id' => 42145, 'name' => 'Sparkling Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye04', 'quality' => 4],
        3736 => ['item_id' => 42146, 'name' => 'Lustrous Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye04', 'quality' => 4],
        3737 => ['item_id' => 42148, 'name' => 'Brilliant Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3738 => ['item_id' => 42149, 'name' => 'Smooth Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3739 => ['item_id' => 42150, 'name' => 'Quick Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3740 => ['item_id' => 42151, 'name' => 'Subtle Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3741 => ['item_id' => 42152, 'name' => 'Flashing Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3742 => ['item_id' => 42156, 'name' => 'Rigid Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3743 => ['item_id' => 42157, 'name' => 'Thick Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3744 => ['item_id' => 42158, 'name' => 'Mystic Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye03', 'quality' => 4],
        3745 => ['item_id' => 42153, 'name' => 'Fractured Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3746 => ['item_id' => 42154, 'name' => 'Precise Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye05', 'quality' => 4],
        3747 => ['item_id' => 42155, 'name' => 'Stormy Dragon\'s Eye', 'icon' => 'inv_jewelcrafting_dragonseye04', 'quality' => 4],
        3879 => ['item_id' => 49110, 'name' => 'Nightmare Tear', 'icon' => 'inv_misc_gem_pearl_12', 'quality' => 4],
    ];
}
