
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-11.4}
    environment:
      MARIADB_DATABASE: ${DB_NAME:-raidbot}
      MARIADB_PASSWORD: ${DB_PASSWORD:-raidbot}
      MARIADB_USER: ${DB_USER:-raidbot}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - mariadb_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  mariadb_data:
###< doctrine/doctrine-bundle ###
